# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: About Us
    path: about-us/1
  - label: Projects
    path: projects/
  - label: News
    path: news/
  - label: Volunteer
    path: volunteer/1
  - label: donate
    path: donate/1
  - label: blog
    path: blog/
  - label: Contact
    link: contact/1
    class: last
